require("config.lazy")
require("config.keymaps")
require("config.set")
require("plugins.mason")
require("plugins.rose-pine")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.autoindent")
